export const Users = [
  {
    id: 1,
    profilePicture: "public/pic1.jpg.jpg",
    username: "Sohail Syed",
  },
  {
    id: 2,
    profilePicture: "public/boy.jpeg",
    username: "Yousuf",
  },
  {
    id: 3,
    profilePicture: "public/boy2.jpeg",
    username: "Faizan",
  },
  {
    id: 4,
    profilePicture: "public/download2.jpg",
    username: "Hamza",
  },
  {
    id: 5,
    profilePicture: "public/girls-lp-hero-image-mobile-data.jpg",
    username: "Tabrej Alam",
  },
  {
    id: 6,
    profilePicture: "public/pic.jpg",
    username: "Sufiyan",
  },
  {
    id: 7,
    profilePicture: "public/360.jpg",
    username: "kashif Qamer",
  },
  {
    id: 8,
    profilePicture: "public/pic2.jpg",
    username: "Abdul Basit",
  },
  {
    id: 9,
    profilePicture: "public/pic3.jpg",
    username: "Sohaib Akhter",
  },
  {
    id: 10,
    profilePicture: "public/pic4.jpg",
    username: "Usman",
  },
];

export const posts = [
  {
    id: 1,
    desc: "love for All Hatred For None.",
    Photo: "public/171.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 85,
    comment: 20,
  },
  {
    id: 2,
    desc: "Dream without fear, love without limits.",
    Photo: "public/aesthetic.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 45,
    comment: 15,
  },
  {
    id: 3,
    desc: "Chasing dreams and catching vibes.",
    Photo: "public/beautiful-nature.webp",
    date: "55 mins ago",
    userId: 3,
    like: 55,
    comment: 13,
  },
  {
    id: 4,
    desc: "Living life, one post at a time.",

    Photo: "public/beautiful.jpg",
    date: "5 hours ago",
    userId: 4,
    like: 8,
    comment: 54,
  },
  {
    id: 5,
    desc: "Living my story, one caption at a time.",
    Photo: "public/istockphoto.webp",
    date: "2 hours ago",
    userId: 5,
    like: 60,
    comment: 25,
  },
  {
    id: 6,
    desc: "Confidence level: Selfie with no filter.",
    Photo: "public/pexels-photo-167964.jpeg",
    date: "2 days ago",
    userId: 6,
    like: 5,
    comment: 29,
  },
  {
    id: 7,
    desc: "Casually conquering the world.",
    Photo: "public/pic5.jpg",
    date: "6 days ago",
    userId: 7,
    like: 26,
    comment: 5,
  },
  {
    id: 8,
    desc: "Too busy being epic to care.",
    Photo: "public/pic6.jpg",
    date: "1 days ago",
    userId: 8,
    like: 17,
    comment: 6,
  },
  {
    id: 9,
    desc: "I was born to stand out.",
    Photo: "public/shadow.jpg",
    date: "2 mins ago",
    userId: 9,
    like: 57,
    comment: 8,
  },
  {
    id: 10,
    desc: "Classy & Fabulous.",
    Photo: "public/article.jpg",
    date: "22 mins ago",
    userId: 10,
    like: 80,
    comment: 3,
  },
];
